test_file = open("test.txt", "w", encoding="utf8")
print("Hello,", file=test_file)
print("Python!", file=test_file)
test_file.close()

test_file = open("test.txt", "a", encoding="utf8")
test_file.write("Nice to ")
test_file.write("Meet You")
print("Python!", file=test_file)
test_file.close()